# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libproj-dev
      - libgdal1-dev
      - libgeos-dev
after_success:
  - Rscript -e 'covr::codecov()'
